// French UI strings. Keys are the English text; tutoiement, friendly product voice.
export default {
  // hero
  'Your AI team · runs on your own machine': 'Ton équipe IA · tourne sur ta propre machine',
  'Your recurring work,': 'Ton travail récurrent,',
  'done while you sleep.': 'fait pendant que tu dors.',
  'Coworkers that': 'Des coworkers qui',
  'Describe a job in your own words. It writes its own prompt, skills and schedule, connects to your tools, and stops to ask you before anything risky.': 'Décris un job avec tes mots. Il écrit son propre prompt, ses skills et son planning, se branche à tes outils, et s’arrête pour te demander avant tout ce qui est risqué.',
  'Find new leads every morning and add them to my list…': 'Trouve de nouveaux leads chaque matin et ajoute-les à ma liste…',
  'Describe the job': 'Décris le job',
  'Describe the job first': 'Décris d’abord le job',
  'Create coworker': 'Créer le coworker',
  'Setting itself up…': 'Il s’installe…',
  coworkers: 'coworkers',
  'working now': 'au travail',
  'waiting for you': 't’attendent',
  'runs · 30 days': 'runs · 30 jours',
  'Offline demo · connect your Claude': 'Démo hors-ligne · connecte ton Claude',
  'Running on {name}': 'Tourne sur {name}',
  'your AI': 'ton IA',
  '{name} wrote its own soul, skills and schedule. Schedules start paused.': '{name} a écrit sa soul, ses skills et son planning. Les plannings démarrent en pause.',
  '{name} is ready. Connect an AI provider so coworkers can draft themselves.': '{name} est prêt. Connecte une IA pour que les coworkers puissent se rédiger eux-mêmes.',

  // sections
  '01 · Headquarters': '01 · Le QG',
  'Your crew, live.': 'Ton équipe, en direct.',
  'Every Box is a floor, every coworker a block that lives on it. Watch them work, see who needs you, and click one to talk to it.': 'Chaque Box est un plateau, chaque coworker un bloc qui y vit. Regarde-les bosser, vois qui a besoin de toi, et clique sur l’un d’eux pour lui parler.',
  'Boxes': 'Boxes',
  'List view': 'Vue liste',
  'Board view': 'Plateau',
  'Colour on the board': 'Couleur sur le plateau',
  Auto: 'Auto',
  '{a} of {b} coworkers working': '{a} coworkers sur {b} au travail',
  'Search coworkers': 'Chercher un coworker',
  'Find a coworker…': 'Trouver un coworker…',
  'No coworker matches.': 'Aucun coworker ne correspond.',
  'Describe a job': 'Décrire un job',
  'Drag to move · pinch to zoom · tap a coworker': 'Glisse pour bouger · pince pour zoomer · touche un coworker',
  'Categories': 'Catégories',
  'Search templates': 'Chercher un template',
  'thinking…': 'réfléchit…',
  List: 'Liste',
  'No coworker yet. Describe a job above, or install one that already works.': 'Aucun coworker pour l’instant. Décris un job plus haut, ou installe-en un qui marche déjà.',
  'Browse templates': 'Voir les templates',
  '02 · Templates': '02 · Templates',
  'Start from a coworker that already works.': 'Pars d’un coworker qui marche déjà.',
  '{n} ready-made coworkers, including the full public library of rerun.build. Each one comes with its soul, its skills, its schedule and a guided setup.': '{n} coworkers prêts à l’emploi, dont toute la bibliothèque publique de rerun.build. Chacun arrive avec sa soul, ses skills, son planning et un setup guidé.',
  'Search: invoices, leads, Shopify, SEO…': 'Cherche : factures, leads, Shopify, SEO…',
  'Install into': 'Installer dans',
  'Share link': 'Lien de partage',
  All: 'Tout',
  yours: 'à toi',
  'guided setup': 'setup guidé',
  'In the app library': 'Dans la bibliothèque d’apps',
  'Connect it with a custom MCP server': 'À brancher via un serveur MCP perso',
  'No app needed': 'Aucune app nécessaire',
  '{n} min setup': '{n} min de setup',
  Install: 'Installer',
  'No template matches.': 'Aucun template ne correspond.',
  'Show more': 'Voir plus',
  'Installed {names}': '{names} installé',
  '{names} installed. Guided setup started: answer its questions.': '{names} installé. Le setup guidé a démarré : réponds à ses questions.',
  '03 · How it works': '03 · Comment ça marche',
  'From a sentence to a coworker that runs on its own.': 'D’une phrase à un coworker qui tourne tout seul.',
  'Give it a job': 'Donne-lui un job',
  'Describe the work in your own words. The coworker writes its own soul, its skills and its schedule.': 'Décris le travail avec tes mots. Le coworker écrit sa soul, ses skills et son planning.',
  'Chase invoices · every Monday': 'Relancer les factures · chaque lundi',
  'Reply to leads · on every new email': 'Répondre aux leads · à chaque nouvel e-mail',
  'Find 20 new leads · every day, 8:00': 'Trouver 20 leads · chaque jour, 8h00',
  'Connect your tools and your AI': 'Branche tes outils et ton IA',
  'Any MCP server, one click for the apps in the library. Your Claude subscription, an API key or a local model.': 'N’importe quel serveur MCP, un clic pour les apps de la bibliothèque. Ton abonnement Claude, une clé API ou un modèle local.',
  'Stripe · active': 'Stripe · actif',
  'Notion · active': 'Notion · actif',
  'Slack · needs a token': 'Slack · token requis',
  'It works, and stops to ask': 'Il bosse, et s’arrête pour demander',
  'Runs on a cron or a webhook. Before paying, emailing a client or deleting, it shows you a card and waits.': 'Il tourne sur un cron ou un webhook. Avant de payer, d’écrire à un client ou de supprimer, il te montre une carte et attend.',
  '07:00 · Sorted the inbox': '07:00 · Boîte mail triée',
  '07:09 · Chased 2 invoices': '07:09 · 2 factures relancées',
  '07:12 · Approval: refund $230?': '07:12 · Validation : rembourser 230 $ ?',
  'Your coworkers used': 'Tes coworkers ont utilisé',
  'tokens in the last 30 days, for {cost}.': 'tokens ces 30 derniers jours, pour {cost}.',
  'Crewbox · everything runs on this machine': 'Crewbox · tout tourne sur cette machine',
  'API & MCP endpoint': 'API & endpoint MCP',

  // dock / nav
  Home: 'Accueil',
  Board: 'QG',
  Templates: 'Templates',
  'To handle': 'À traiter',
  Notifications: 'Notifications',
  'Knowledge base': 'Base de connaissances',
  Settings: 'Réglages',
  'New coworker': 'Nouveau coworker',

  // world
  '{n} working': '{n} au travail',
  '{n} waiting for you': '{n} t’attendent',
  'Zoom in': 'Zoomer',
  'Zoom out': 'Dézoomer',
  Recenter: 'Recentrer',
  'Switched off': 'Éteint',
  'Add a coworker': 'Ajouter un coworker',
  'Rename Box': 'Renommer la Box',
  'Delete Box': 'Supprimer la Box',
  'New Box': 'Nouvelle Box',
  'A team, a client or a project': 'Une équipe, un client ou un projet',
  'Sales team': 'Équipe commerciale',
  '{n} coworker': '{n} coworker',
  '{n} coworkers': '{n} coworkers',
  '{n} Box': '{n} Box',
  '{n} Boxes': '{n} Boxes',
  '{n} skill': '{n} skill',
  '{n} skills': '{n} skills',
  '{n} schedule': '{n} planning',
  '{n} schedules': '{n} plannings',
  Open: 'Ouvrir',
  off: 'éteint',
  on: 'actif',
  paused: 'en pause',

  // statuses
  Ready: 'Prêt',
  Working: 'Au travail',
  'Needs you': 'Besoin de toi',
  Error: 'Erreur',
  'Working…': 'En cours…',
  active: 'actif',
  needs_config: 'à configurer',
  done: 'terminé',
  running: 'en cours',
  waiting: 'en attente',
  cancelled: 'annulé',
  'just now': 'à l’instant',
  '{n} min ago': 'il y a {n} min',
  '{n} h ago': 'il y a {n} h',

  // categories
  Sales: 'Ventes', 'E-commerce': 'E-commerce', Productivity: 'Productivité', Agencies: 'Agences', 'Real estate': 'Immobilier', Creators: 'Créateurs',
  'Legal & compliance': 'Juridique & conformité', Recruiting: 'Recrutement', SaaS: 'SaaS', Finance: 'Finance', Marketing: 'Marketing',
  'Customer support': 'Support client', Operations: 'Opérations', Research: 'Recherche', Other: 'Autre',

  // providers
  'Claude subscription (Pro / Max)': 'Abonnement Claude (Pro / Max)',
  'Anthropic API key': 'Clé API Anthropic',
  'Google Gemini (OpenAI-compatible)': 'Google Gemini (compatible OpenAI)',
  'Local model (Ollama / LM Studio / vLLM)': 'Modèle local (Ollama / LM Studio / vLLM)',
  'Offline demo (no AI)': 'Démo hors-ligne (sans IA)',

  // panel
  Chat: 'Chat', Skills: 'Skills', Automations: 'Automatisations', Apps: 'Apps', Memory: 'Mémoire', Database: 'Base de données', Files: 'Fichiers', Runs: 'Runs',
  Close: 'Fermer',
  Conversation: 'Conversation',
  'No conversation yet': 'Pas encore de conversation',
  New: 'Nouveau',
  Model: 'Modèle',
  'Model updated': 'Modèle mis à jour',
  'Give {name} a job.': 'Donne un job à {name}.',
  'What can you do for me?': 'Qu’est-ce que tu peux faire pour moi ?',
  'Set up your first scheduled task': 'Crée ta première tâche planifiée',
  'Show me what you remember': 'Montre-moi ce dont tu te souviens',
  'Answer the card, or type your reply here…': 'Réponds à la carte, ou écris ta réponse ici…',
  'Message {name}…': 'Écris à {name}…',
  Message: 'Message',
  Send: 'Envoyer',
  Stop: 'Arrêter',
  Input: 'Entrée',
  Result: 'Résultat',
  'A question for you': 'Une question pour toi',
  'Approval required': 'Validation requise',
  'Connect an app': 'Connecte une app',
  'A credential is needed': 'Il faut un identifiant',
  'Something else…': 'Autre chose…',
  Approve: 'Valider',
  Decline: 'Refuser',
  Run: 'Lancer',
  'Allow once': 'Autoriser une fois',
  'This session': 'Pour cette session',
  Always: 'Toujours',
  Deny: 'Refuser',
  'Stored on this machine as': 'Stocké sur cette machine sous',
  'Skip for now': 'Plus tard',
  'Cancel run': 'Annuler le run',
  'Send answer': 'Envoyer la réponse',
  'Waiting for you': 'En attente de toi',
  'Cards your coworker raised. Nothing is skipped because nobody was watching.': 'Les cartes levées par ton coworker. Rien n’est sauté parce que personne ne regardait.',
  'Nothing is waiting for you.': 'Rien ne t’attend.',
  'Nothing is waiting for you. Your crew is on it.': 'Rien ne t’attend. Ton équipe gère.',
  'No notifications.': 'Aucune notification.',
  'Mark all read': 'Tout marquer comme lu',
  'Open {name}': 'Ouvrir {name}',
  'Open conversation': 'Ouvrir la conversation',

  // skills
  'Procedures it opens only when a task matches the description. Only the one-line index stays in its context.': 'Des procédures qu’il n’ouvre que quand une tâche correspond à la description. Seul l’index d’une ligne reste dans son contexte.',
  'New skill': 'Nouveau skill',
  Skill: 'Skill',
  'No skill yet. Tell the coworker “remember this procedure as a skill”, or write one.': 'Pas encore de skill. Dis au coworker « retiens cette procédure en skill », ou écris-en un.',
  'Delete skill': 'Supprimer le skill',
  Name: 'Nom',
  Description: 'Description',
  'a trigger condition: “Use when…”': 'une condition de déclenchement : « À utiliser quand… »',
  Procedure: 'Procédure',
  'SKILL.md body': 'corps du SKILL.md',
  'Reference files': 'Fichiers de référence',
  'Loaded only when the procedure points at them.': 'Chargés seulement quand la procédure les cite.',
  File: 'Fichier',
  'This skill belongs to the app': 'Ce skill appartient à l’app',
  'Save skill': 'Enregistrer le skill',
  'Skill saved': 'Skill enregistré',

  // automations
  'Scheduled tasks': 'Tâches planifiées',
  'A cron or a date, plus an instruction. Each run opens its own session; memory and databases carry over.': 'Un cron ou une date, plus une consigne. Chaque run ouvre sa propre session ; la mémoire et les bases suivent.',
  Schedule: 'Planifier',
  'No scheduled task.': 'Aucune tâche planifiée.',
  'Run now': 'Lancer maintenant',
  Fired: 'Lancé',
  Pause: 'Pause',
  Enable: 'Activer',
  Disable: 'Désactiver',
  'Delete scheduled task': 'Supprimer la tâche planifiée',
  'New scheduled task': 'Nouvelle tâche planifiée',
  'Edit · {name}': 'Modifier · {name}',
  'Monday chase': 'Relance du lundi',
  Instruction: 'Consigne',
  'the whole prompt of that run': 'tout le prompt de ce run',
  When: 'Quand',
  'Recurring (cron)': 'Récurrent (cron)',
  'Once, at a date': 'Une fois, à une date',
  Cron: 'Cron',
  'minute hour day month weekday': 'minute heure jour mois jour-de-semaine',
  'Weekdays 8:00': 'Semaine 8h00',
  'Mondays 9:00': 'Lundis 9h00',
  'Every hour': 'Toutes les heures',
  'Daily 7:00': 'Chaque jour 7h00',
  'Date and time': 'Date et heure',
  Timezone: 'Fuseau horaire',
  IANA: 'IANA',
  Enabled: 'Activé',
  Save: 'Enregistrer',
  Saved: 'Enregistré',
  'Webhook triggers': 'Triggers webhook',
  'A public URL that starts a run. The URL is the credential: keep it secret, rotate it if it leaks.': 'Une URL publique qui lance un run. L’URL est le secret : garde-la pour toi, régénère-la si elle fuit.',
  Trigger: 'Trigger',
  'No trigger.': 'Aucun trigger.',
  URL: 'URL',
  'URL copied': 'URL copiée',
  Test: 'Tester',
  'Test the trigger': 'Tester le trigger',
  'Payload (JSON or text). This is a real fire.': 'Payload (JSON ou texte). C’est un vrai déclenchement.',
  Fire: 'Déclencher',
  Rotate: 'Régénérer',
  'Rotate the URL': 'Régénérer l’URL',
  'The current URL stops working immediately; update every service using it.': 'L’URL actuelle cesse de marcher tout de suite ; mets à jour chaque service qui l’utilise.',
  'Delete trigger': 'Supprimer le trigger',
  'Show URL': 'Afficher l’URL',
  'New webhook trigger': 'Nouveau trigger webhook',
  'the URL is built from it and cannot be renamed later': 'l’URL est construite à partir du nom, impossible de le changer ensuite',
  'Stripe payment': 'Paiement Stripe',
  'write it as if the event had already happened': 'écris-la comme si l’événement venait d’arriver',
  'A Stripe payment event arrives. Record it in the payments table and tell me if it is over 500.': 'Un paiement Stripe arrive. Enregistre-le dans la table payments et préviens-moi s’il dépasse 500.',
  'Accepted methods': 'Méthodes acceptées',
  'Accepting GET means a link preview could fire it. Keep POST unless the caller cannot send it.': 'Accepter GET veut dire qu’un aperçu de lien pourrait le déclencher. Garde POST sauf si l’appelant ne peut pas l’envoyer.',
  'Create trigger': 'Créer le trigger',

  // apps
  Installed: 'Installées',
  'Each app is an MCP server plus a skill on how to use it.': 'Chaque app est un serveur MCP plus un skill qui explique comment s’en servir.',
  'No app yet. Install one below, or ask the coworker: it searches the library and raises a setup card.': 'Pas encore d’app. Installe-en une ci-dessous, ou demande au coworker : il cherche dans la bibliothèque et lève une carte de configuration.',
  Connect: 'Connecter',
  'Connect {name}': 'Connecter {name}',
  'Remove {name}': 'Retirer {name}',
  'Its tools and skill go away with it.': 'Ses outils et son skill partent avec.',
  Remove: 'Retirer',
  Library: 'Bibliothèque',
  'Search apps…': 'Chercher une app…',
  'Custom MCP': 'MCP perso',
  'Custom MCP server': 'Serveur MCP perso',
  installed: 'installée',
  '{name} connected': '{name} connecté',
  '{name} · {n} tools': '{name} · {n} outils',
  Credentials: 'Identifiants',
  Variable: 'Variable',
  'Always allowed': 'Toujours autorisés',
  'Tools that run without asking.': 'Les outils qui tournent sans demander.',
  'Ask again': 'Redemander',
  'VARIABLE_NAME': 'NOM_DE_VARIABLE',
  value: 'valeur',
  'Stored on this machine only. The coworker learns that the variable exists, never its value.': 'Stocké uniquement sur cette machine. Le coworker sait que la variable existe, jamais sa valeur.',
  'Anything that speaks the Model Context Protocol works. Reference credentials as': 'Tout ce qui parle le Model Context Protocol marche. Référence les identifiants avec',
  Transport: 'Transport',
  Command: 'Commande',
  Arguments: 'Arguments',
  'space-separated': 'séparés par des espaces',
  Environment: 'Environnement',
  JSON: 'JSON',
  Headers: 'En-têtes',
  Register: 'Enregistrer',

  // memory
  'Durable facts it recalls. Unused memories fade; every recall extends their life.': 'Des faits durables qu’il se rappelle. Les souvenirs inutilisés s’effacent ; chaque rappel prolonge leur vie.',
  '“Never email clients before 9am.”': '« N’écris jamais aux clients avant 9h. »',
  Add: 'Ajouter',
  'Nothing remembered yet. Correct it once and it remembers.': 'Rien en mémoire pour l’instant. Corrige-le une fois et il s’en souvient.',
  'Edit memory': 'Modifier le souvenir',
  Edit: 'Modifier',
  Forget: 'Oublier',

  // data & files
  'No table yet. Coworkers create tables as they work: leads, invoices, tickets…': 'Pas encore de table. Les coworkers en créent en bossant : leads, factures, tickets…',
  'Search…': 'Rechercher…',
  '{n} rows': '{n} lignes',
  CSV: 'CSV',
  'Delete selected': 'Supprimer la sélection',
  'Delete rows': 'Supprimer des lignes',
  'Delete {n} selected rows?': 'Supprimer les {n} lignes sélectionnées ?',
  'Drop table': 'Supprimer la table',
  'Drop {name}': 'Supprimer {name}',
  'The whole table and its rows will be deleted.': 'Toute la table et ses lignes seront supprimées.',
  'by {who}': 'par {who}',
  Upload: 'Importer',
  Uploaded: 'Importé',
  workspace: 'espace de travail',
  shared: 'partagé',
  'Drop files here to give the coworker something to work on. Its deliverables land here too.': 'Dépose des fichiers ici pour donner du travail au coworker. Ses livrables arrivent ici aussi.',
  'Every coworker reads and writes this folder: it is how they hand files to each other.': 'Tous les coworkers lisent et écrivent ce dossier : c’est comme ça qu’ils se passent des fichiers.',
  'Empty folder.': 'Dossier vide.',
  Download: 'Télécharger',
  Delete: 'Supprimer',
  'Delete {name}?': 'Supprimer {name} ?',
  'Shared by every coworker of the workspace, whichever Box they sit in.': 'Partagée par tous les coworkers de l’espace, quelle que soit leur Box.',
  'Shared folder': 'Dossier partagé',
  'Shared database': 'Base partagée',

  // runs
  'No run yet.': 'Aucun run pour l’instant.',
  'Loading…': 'Chargement…',

  // settings tab
  Handle: 'Handle',
  'others call it @handle': 'les autres l’appellent @handle',
  Soul: 'Soul',
  'who it is, what it owns, how it works, what it must never do': 'qui il est, ce dont il est responsable, comment il bosse, ce qu’il ne doit jamais faire',
  'Answer length': 'Longueur des réponses',
  Box: 'Box',
  Capabilities: 'Capacités',
  'Families of tools. Turn off what it has no business doing.': 'Des familles d’outils. Coupe ce qui ne le regarde pas.',
  'Ask me before': 'Demande-moi avant',
  'appWrites = any app tool that is not read-only.': 'appWrites = tout outil d’app qui n’est pas en lecture seule.',
  'Self-improvement': 'Auto-amélioration',
  'Switch off': 'Éteindre',
  'Switch on': 'Allumer',
  'Save as template': 'Enregistrer comme template',
  'Saved as local template “{name}”': 'Enregistré comme template local « {name} »',
  'Share link copied: {path}': 'Lien de partage copié : {path}',
  'Delete {name}': 'Supprimer {name}',
  'Its skills, memory, files, schedules and history are deleted for good.': 'Ses skills, sa mémoire, ses fichiers, ses plannings et son historique sont supprimés pour de bon.',

  // dialogs
  Cancel: 'Annuler',
  Confirm: 'Confirmer',
  'Type {word} to confirm': 'Tape {word} pour confirmer',
  'What is the job?': 'C’est quoi le job ?',
  'in your own words — it writes its own prompt, skills and schedule': 'avec tes mots — il écrit son prompt, ses skills et son planning',
  'Every morning, find 20 SaaS companies in France that just started hiring salespeople and add them to my leads table.': 'Chaque matin, trouve 20 SaaS en France qui viennent de recruter des commerciaux et ajoute-les à ma table de leads.',
  'Start blank': 'Partir de zéro',
  'Margo · Invoice Chasing': 'Margo · Relance factures',
  'One line on what it is for': 'Une ligne sur ce à quoi il sert',
  'the system prompt, in markdown': 'le prompt système, en markdown',
  Create: 'Créer',
  'Install from a share link': 'Installer depuis un lien de partage',
  'Share link (…/s/<token>) or template JSON URL': 'Lien de partage (…/s/<token>) ou URL d’un template JSON',

  // settings dialog
  'AI providers': 'Fournisseurs d’IA',
  'API & MCP': 'API & MCP',
  'Workspace secrets': 'Secrets de l’espace',
  'What your coworkers think with. Each one follows the workspace default unless you pin a model for it.': 'Ce avec quoi tes coworkers réfléchissent. Chacun suit le choix par défaut, sauf si tu lui épingles un modèle.',
  connected: 'connecté',
  'needs key': 'clé requise',
  'Coworkers pinned to it go back to the default.': 'Les coworkers épinglés dessus repassent sur le modèle par défaut.',
  'Default model:': 'Modèle par défaut :',
  'Add a provider': 'Ajouter un fournisseur',
  'Add an AI provider': 'Ajouter un fournisseur d’IA',
  'Edit {name}': 'Modifier {name}',
  Provider: 'Fournisseur',
  'API key': 'Clé API',
  'stays on this machine': 'reste sur cette machine',
  'Base URL': 'URL de base',
  'OpenAI-compatible: Ollama, LM Studio, vLLM, OpenRouter…': 'compatible OpenAI : Ollama, LM Studio, vLLM, OpenRouter…',
  Models: 'Modèles',
  'comma-separated ids': 'identifiants séparés par des virgules',
  'One MCP endpoint to build and drive your coworkers from Claude Code, Codex, Cursor or a script. JSON-RPC 2.0 over POST, the same tool names as the Rerun API.': 'Un endpoint MCP pour créer et piloter tes coworkers depuis Claude Code, Codex, Cursor ou un script. JSON-RPC 2.0 en POST, les mêmes noms d’outils que l’API Rerun.',
  Endpoint: 'Endpoint',
  Webhooks: 'Webhooks',
  'API keys': 'Clés API',
  'New key': 'Nouvelle clé',
  'New API key': 'Nouvelle clé API',
  'No key yet.': 'Pas encore de clé.',
  Revoke: 'Révoquer',
  'Your new API key': 'Ta nouvelle clé API',
  'Copy it now: it is shown once and reaches every coworker of this workspace.': 'Copie-la maintenant : elle n’est affichée qu’une fois et donne accès à tous les coworkers de l’espace.',
  'Connect Claude Code:': 'Connecter Claude Code :',
  'Or call it with curl:': 'Ou appelle-la avec curl :',
  "Shared by every coworker; a coworker's own variable with the same name wins.": 'Partagés par tous les coworkers ; la variable propre d’un coworker portant le même nom gagne.',
  'Claude subscription': 'Abonnement Claude',
  'Default ({model})': 'Par défaut ({model})',
  'Your coworkers run through Claude Code with your Pro or Max subscription: no API key, usage counts against your plan.': 'Tes coworkers tournent via Claude Code avec ton abonnement Pro ou Max : pas de clé API, l’usage est décompté de ton forfait.',
  'On this machine, run this once in a terminal and paste the token below:': 'Sur cette machine, lance une fois cette commande dans un terminal et colle le token ci-dessous :',
  'Already logged in to Claude Code here? You can leave the token empty.': 'Déjà connecté à Claude Code sur cette machine ? Tu peux laisser le token vide.',
  'Subscription token': 'Token d’abonnement',
  '(unchanged)': '(inchangé)',
  'Use your Claude plan': 'Utilise ton abonnement Claude',
  'Token from `claude setup-token`': 'Token de `claude setup-token`',

  // Foreman, Brain, Autopilot, apps
  "Accept": "Accepter",
  "Add a rule": "Ajouter une règle",
  "Analyze my site": "Analyser mon site",
  "Answer customer support requests": "Répondre aux demandes du support client",
  "Approve cold emails to new leads, at most 30 a day.": "Approuve les emails de prospection vers de nouveaux leads, 30 par jour maximum.",
  "Approve replies to customers that only answer a question from the FAQ.": "Approuve les réponses aux clients qui reprennent seulement une question de la FAQ.",
  "Ask Foreman, your assistant": "Demande à Foreman, ton assistant",
  "Autopilot": "Pilote auto",
  "Autopilot answers your coworkers within your rules: when a card is covered by one of them, it decides for you and tells you why. Everything else, and every credential, still waits for you.": "Le pilote auto répond à tes coworkers selon tes règles : quand une carte est couverte par l’une d’elles, il décide à ta place et te dit pourquoi. Tout le reste, et chaque identifiant, t’attend toujours.",
  "Brain": "Cerveau",
  "Brain pages": "Pages du Cerveau",
  "Brain updated": "Cerveau mis à jour",
  "Build my team": "Construire mon équipe",
  "Building your team…": "Je construis ton équipe…",
  "Built from Foreman’s recipes (no AI connected). Connect Claude for a plan written for your company.": "Construit à partir des recettes de Foreman (aucune IA connectée). Connecte Claude pour un plan écrit pour ton entreprise.",
  "Change": "Modifier",
  "Change something": "Changer quelque chose",
  "Changes": "Modifications",
  "Company pages": "Pages entreprise",
  "Connect Claude": "Connecter Claude",
  "Connected": "Connecté",
  "Content": "Contenu",
  "Coworker": "Coworker",
  "Create a free developer app on the service, paste its ID and secret once, then sign in.": "Crée une app développeur gratuite sur le service, colle son ID et son secret une fois, puis connecte-toi.",
  "Demo mode: with no AI connected, Foreman uses its proven team recipes. Connect your Claude subscription for a plan written for your company.": "Mode démo : sans IA connectée, Foreman utilise ses recettes d’équipe éprouvées. Connecte ton abonnement Claude pour un plan écrit pour ton entreprise.",
  "Design my team": "Concevoir mon équipe",
  "Designing your team…": "Je conçois ton équipe…",
  "During setup it will ask you:": "Pendant la configuration, il te demandera :",
  "Find leads and send them personal cold emails": "Trouver des leads et leur envoyer des emails de prospection personnalisés",
  "Fridays": "le vendredi",
  "Get a weekly report of my numbers": "Recevoir un rapport hebdo de mes chiffres",
  "Give me your website: I read it, understand your business, and build you a team of coworkers that fits it.": "Donne-moi ton site : je le lis, je comprends ton business, et je te construis une équipe de coworkers sur mesure.",
  "Here is what I understood about {name}": "Voilà ce que j’ai compris de {name}",
  "Hi, I'm Foreman.": "Salut, moi c’est Foreman.",
  "How to connect": "Comment connecter",
  "I don't have a website yet": "Je n’ai pas encore de site",
  "It works right away.": "Ça marche tout de suite.",
  "Its day": "Sa journée",
  "Its first week": "Sa première semaine",
  "Local command": "Commande locale",
  "MCP only": "MCP uniquement",
  "Mondays": "le lundi",
  "Mon–Fri": "Lun–Ven",
  "Never approve a refund, a payment or a deletion.": "N’approuve jamais un remboursement, un paiement ou une suppression.",
  "New page": "Nouvelle page",
  "No app matches. Add it as a custom MCP server.": "Aucune app ne correspond. Ajoute-la comme serveur MCP personnalisé.",
  "No decision yet.": "Aucune décision pour l’instant.",
  "Nothing to connect": "Rien à connecter",
  "Off": "Désactivé",
  "On": "Activé",
  "Opening your site…": "J’ouvre ton site…",
  "Paste a key from your account. It goes straight to this machine, never to the AI.": "Colle une clé de ton compte. Elle va directement sur cette machine, jamais à l’IA.",
  "Plain sentences. Autopilot only acts when a rule clearly covers the card.": "Des phrases simples. Le pilote auto n’agit que quand une règle couvre clairement la carte.",
  "Proposals": "Propositions",
  "REST API · {n} tools": "API REST · {n} outils",
  "Read my website": "Lire mon site",
  "Reading {site}…": "Je lis {site}…",
  "Recent decisions": "Décisions récentes",
  "Redesign": "Refaire",
  "Redirect URI to register in your app:": "URI de redirection à enregistrer dans ton app :",
  "Reject": "Refuser",
  "Rule {n}": "Règle {n}",
  "Runs the official MCP server on this machine (needs Node.js).": "Lance le serveur MCP officiel sur cette machine (Node.js requis).",
  "Saturdays": "le samedi",
  "Save rules": "Enregistrer les règles",
  "Search apps… (e.g. send emails, CRM, Stripe)": "Chercher une app… (ex. envoyer des emails, CRM, Stripe)",
  "Set up a team with Foreman": "Monter une équipe avec Foreman",
  "Set up your team with Foreman": "Monte ton équipe avec Foreman",
  "Sign in": "Se connecter",
  "Sign in to {name}": "Se connecter à {name}",
  "Sign in with your app": "Se connecter avec ton app",
  "Skills, schedules and apps…": "Skills, plannings et apps…",
  "Skip": "Passer",
  "Sundays": "le dimanche",
  "The Brain is empty. Let Foreman read your website, or write the first page.": "Le Cerveau est vide. Laisse Foreman lire ton site, ou écris la première page.",
  "Thursdays": "le jeudi",
  "Title": "Titre",
  "Tools spotted on your site": "Outils repérés sur ton site",
  "Tuesdays": "le mardi",
  "Understanding your business…": "Je comprends ton business…",
  "Wednesdays": "le mercredi",
  "What do you want your team to do for you?": "Qu’est-ce que tu veux que ton équipe fasse pour toi ?",
  "What should change? e.g. \"only one coworker\", \"use Gmail instead of Resend\"": "Qu’est-ce qu’on change ? ex. « un seul coworker », « Gmail au lieu de Resend »",
  "Where your company lives: every coworker reads these pages before it works. When one learns something worth keeping, it proposes a change; nothing moves until you accept it.": "Là où vit ton entreprise : chaque coworker lit ces pages avant de bosser. Quand l’un d’eux apprend quelque chose qui vaut le coup, il propose une modif ; rien ne bouge tant que tu n’as pas accepté.",
  "Who does what, with which apps, and when.": "Qui fait quoi, avec quelles apps, et quand.",
  "You sign in on the service. Crewbox keeps the access on this machine.": "Tu te connectes sur le service. Crewbox garde l’accès sur cette machine.",
  "Your goal": "Ton objectif",
  "Your rules": "Tes règles",
  "Your website": "Ton site",
  "answered": "répondu",
  "apps to connect": "apps à connecter",
  "community server": "serveur communautaire",
  "e.g. find leads every morning and send them personal cold emails with Resend": "ex. trouver des leads chaque matin et leur envoyer des emails de prospection personnalisés avec Resend",
  "every day": "tous les jours",
  "from your website": "tiré de ton site",
  "in error": "en erreur",
  "left to you": "laissé à toi",
  "markdown": "markdown",
  "official MCP": "MCP officiel",
  "owner": "toi",
  "proposed by a coworker": "proposé par un coworker",
  "to configure": "à configurer",
  "to sign in": "à connecter",
  "unavailable": "indisponible",
  "waiting for you · {n}": "t’attend · {n}",
  "waits for you": "t’attend",
  "website": "site",
  "working": "au travail",
  "written by you": "écrit par toi",
  "{days} at {time}": "{days} à {time}",
  "{name} has no public integration yet. Add its MCP server yourself (Custom MCP).": "{name} n’a pas encore d’intégration publique. Ajoute son serveur MCP toi-même (MCP perso).",
  "{n} apps: everything rerun.build connects, plus any MCP server.": "{n} apps : tout ce que rerun.build connecte, plus n’importe quel serveur MCP.",
  "{n} coworkers built. Each one starts its guided setup.": "{n} coworkers construits. Chacun démarre sa configuration guidée.",
  "{n} pages read · saved in the Brain, every coworker reads it": "{n} pages lues · enregistrées dans le Cerveau, chaque coworker les lit",
};
